pimcore:
  workflows:
    product_workflow:
      label: "Simple Product Workflow"
      type: "state_machine"
      supports:
        - \Pimcore\Model\DataObject\Product
        - \Pimcore\Model\DataObject\Advisory
      initial_markings: new

      places:
        new:
          label: "new"
          title: "Product Magic did not start"
          color: "#3572b0"
          colorInverted: true
          permissions:
            - publish: false
              unpublish: false
              save: true
              delete: false
        edit:
          label: "edit"
          title: "Edit"
          color: "#3572b0"
          colorInverted: true
          permissions:
            - publish: false
              unpublish: false
              save: true
              delete: false
        review:
          label: "review"
          title: "Review"
          color: "#3572b0"
          colorInverted: true
          permissions:
            - publish: false
              unpublish: false
              save: false
              delete: false
        complete:
          label: "complete"
          title: "Complete"
          color: "#3572b0"
          colorInverted: true
          permissions:
            - publish: false
              unpublish: false
              save: false
              delete: false
      transitions:
        start_work:
          from: "new"
          to: "edit"
          options:
            label: "Start Work"
        sent_to_review:
          from: "edit"
          to: "review"
          options:
            label: "Send To Review"
        approve:
          from: "review"
          to: "complete"
          options:
            label: "Approved"
            changePublishedState: force_published
        back_to_edit:
          from: "complete"
          to: "edit"
          options:
            label: "Back To Edit"
            changePublishedState: force_unpublished
        rejected:
          from: "review"
          to: "edit"
          options:
            label: "Recjected"
